server:
  port: 5678

spring:
#  zipkin:
#    base-url: http://localhost:9411/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${USER_NAME:postgres}
    password: ${PASSWORD:mysecretpassword}
    url: ${URL:jdbc:postgresql://localhost:5433/postgres}
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: ms-orders

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8701/eureka/